# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_precautionary_wrappers", use_symbols = TRUE, package_name = "precautionary")

#' @docType package
#' @usage NULL
#' @useDynLib precautionary, .registration = TRUE
NULL

#' Rust implementation of \code{dfcrm::crmh*} integrands
#'
#' @param a Numeric vector of evaluation points
#' @param x Numeric vector of dose-wise prior probabilities of toxicity
#' @param y Integer vector of patient-wise 0/1 toxicity indicators
#' @param w Patient-wise weights (used for TITE CRM)
#' @param s Scalar scale factor
#' @describeIn crmh Posterior for 1-parameter empiric (aka 'power') model
#' @export
crmh <- function(a, x, y, w, s) .Call(wrap__crmh, a, x, y, w, s)

#' @describeIn crmh Integrand for 1st moment of empiric posterior
#' @export
crmht <- function(a, x, y, w, s) .Call(wrap__crmht, a, x, y, w, s)

#' @describeIn crmh Integrand for 2nd moment of empiric posterior
#' @export
crmht2 <- function(a, x, y, w, s) .Call(wrap__crmht2, a, x, y, w, s)

