# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_precautionary_wrappers", use_symbols = TRUE, package_name = "precautionary")

#' @docType package
#' @usage NULL
#' @useDynLib precautionary, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Return string `"Adios, C!"` to R.
#' @export
adios <- function() .Call(wrap__adios)

#' A Rust implementation of the dfcrm::crmh posterior, which I hope will prove
#' faster to integrate() than my tuned-up (2x) reimplementation of Ken Cheung's
#' R code from package 'dfcrm'.
#' @export
rcrmh <- function(a, x, y, w, s) .Call(wrap__rcrmh, a, x, y, w, s)

rcrmht <- function(a, x, y, w, s) .Call(wrap__rcrmht, a, x, y, w, s)

rcrmht2 <- function(a, x, y, w, s) .Call(wrap__rcrmht2, a, x, y, w, s)

